// UC data — Phần 1: Chung, Quản lý tài khoản, Quản lý phương tiện
module.exports = {
  general: [
    {
      id: 'UC1', name: 'Đăng nhập',
      objective: 'Cho phép người dùng (Nhân viên, Khách hàng) đăng nhập vào hệ thống bằng định danh và mật khẩu.',
      actors: 'Nhân viên (Staff), Khách hàng (Customer)',
      trigger: 'Người dùng truy cập màn hình Đăng nhập và gửi thông tin đăng nhập.',
      pre: 'Người dùng chưa đăng nhập. • Người dùng đã có tài khoản đang hoạt động (IsActive = true).',
      post: 'Phiên làm việc (session) phía máy chủ được tạo với AccountId. • Người dùng được chuyển hướng đến trang chủ phù hợp với vai trò.',
      steps: [
        'Người dùng truy cập màn hình Đăng nhập (qua Mobile Web đối với Khách hàng).',
        'Người dùng nhập Định danh (email hoặc số điện thoại) và Mật khẩu, sau đó nhấn Đăng nhập.',
        'Hệ thống (Account Service) kiểm tra hai trường Định danh và Mật khẩu không được để trống.',
        'Hệ thống tìm bản ghi Account theo email hoặc số điện thoại.',
        'Hệ thống kiểm tra tài khoản đang ở trạng thái hoạt động (IsActive = true).',
        'Hệ thống đối chiếu mật khẩu với chuỗi băm (hash) đã lưu.',
        'Hệ thống tạo session phía máy chủ và thiết lập cookie xác thực.',
        'Hệ thống trả về phản hồi đăng nhập: vai trò, họ tên, email, số điện thoại.',
        'Ứng dụng chuyển hướng theo vai trò: Nhân viên → màn hình Quản lý hàng chờ; Khách hàng → Trang chủ khách hàng.',
      ],
      brs: [
        { step: 3, desc: 'Nếu Định danh hoặc Mật khẩu để trống, hiển thị MSG1: "Vui lòng nhập đầy đủ các trường bắt buộc."' },
        { step: 4, desc: 'Nếu không tìm thấy tài khoản, hiển thị MSG2: "Tên đăng nhập hoặc mật khẩu không đúng."' },
        { step: 5, desc: 'Nếu tài khoản tồn tại nhưng IsActive = false (đã bị nhân viên vô hiệu hóa — UC6), từ chối đăng nhập và hiển thị MSG26.' },
        { step: 6, desc: 'Nếu mật khẩu không khớp chuỗi băm, hiển thị MSG2. Đăng nhập chỉ dùng mật khẩu, không yêu cầu OTP.' },
        { step: 7, desc: 'Thời gian chờ (idle timeout) của session là 8 giờ. Cookie được đặt cờ HttpOnly.' },
        { step: 9, desc: 'Ánh xạ vai trò: Account.Role 1 = Nhân viên, 2 = Khách hàng.' },
      ],
    },
    {
      id: 'UC2', name: 'Đăng xuất',
      objective: 'Cho phép người dùng đã đăng nhập thoát khỏi hệ thống.',
      actors: 'Nhân viên, Khách hàng',
      trigger: 'Người dùng nhấn nút Đăng xuất từ bất kỳ màn hình nào.',
      pre: 'Người dùng đang đăng nhập với session còn hiệu lực.',
      post: 'Session bị xóa. Cookie xác thực bị hủy. Người dùng được chuyển về màn hình Đăng nhập.',
      steps: [
        'Người dùng chọn Đăng xuất trên thanh điều hướng.',
        'Hệ thống xóa session phía máy chủ.',
        'Hệ thống xóa các cookie xác thực.',
        'Hệ thống chuyển hướng người dùng về màn hình Đăng nhập.',
      ],
      brs: [],
    },
  ],
  account: [
    {
      id: 'UC3', name: 'Đăng ký tài khoản',
      objective: 'Cho phép khách truy cập mới tạo tài khoản Khách hàng với xác thực OTP qua email.',
      actors: 'Khách hàng (người dùng mới)',
      trigger: 'Người dùng mở màn hình Đăng ký trên Mobile Web và gửi biểu mẫu.',
      pre: 'Người dùng chưa đăng nhập. • Địa chỉ email chưa từng được đăng ký trong hệ thống.',
      post: 'Bản ghi Account mới được tạo (Role = Khách hàng, IsActive = true). • Bản ghi Customer mới được tạo và liên kết với Account.',
      steps: [
        'Người dùng mở màn hình Đăng ký trên Mobile Web.',
        'Người dùng nhập địa chỉ email và nhấn "Gửi OTP".',
        'Notification Service sinh mã OTP 6 chữ số (lưu dạng băm, hiệu lực 5 phút) và gửi đến email qua máy chủ Email SMTP.',
        'Người dùng nhập Họ tên, Số điện thoại, Mật khẩu và mã OTP nhận được.',
        'Người dùng gửi biểu mẫu đăng ký.',
        'Hệ thống kiểm tra OTP: khớp mã, chưa hết hạn, chưa được sử dụng.',
        'Hệ thống kiểm tra email chưa được đăng ký.',
        'Hệ thống kiểm tra số điện thoại (nếu có) chưa được sử dụng.',
        'Hệ thống tạo bản ghi Account với mật khẩu đã băm.',
        'Hệ thống tạo bản ghi Customer liên kết với Account.',
        'Hệ thống chuyển người dùng đến màn hình Đăng nhập hoặc tự động đăng nhập.',
      ],
      brs: [
        { step: 3, desc: 'OTP là mã số 6 chữ số, hiệu lực 5 phút kể từ thời điểm sinh mã (CBR3).' },
        { step: 6, desc: 'Nếu OTP hết hạn, hiển thị MSG4. Nếu OTP sai hoặc đã dùng, hiển thị MSG5.' },
        { step: 7, desc: 'Nếu email đã được đăng ký, hiển thị MSG3 và đề nghị người dùng chuyển sang màn hình Đăng nhập (UC1).' },
        { step: 8, desc: 'Nếu số điện thoại đã được sử dụng, hiển thị MSG20.' },
        { step: 9, desc: 'Mật khẩu được lưu dưới dạng băm mật mã. Không bao giờ lưu mật khẩu dạng văn bản thuần.' },
      ],
    },
    {
      id: 'UC4', name: 'Cập nhật hồ sơ',
      objective: 'Cho phép khách hàng cập nhật họ tên và số điện thoại.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng mở màn hình Cài đặt hồ sơ và gửi thay đổi.',
      pre: 'Khách hàng đã đăng nhập.',
      post: 'Account.FullName và Account.Phone được cập nhật trong cơ sở dữ liệu.',
      steps: [
        'Khách hàng mở màn hình Cài đặt hồ sơ.',
        'Khách hàng chỉnh sửa Họ tên và/hoặc Số điện thoại.',
        'Khách hàng nhấn Lưu.',
        'Hệ thống kiểm tra Họ tên không được để trống.',
        'Hệ thống kiểm tra số điện thoại mới (nếu thay đổi) là duy nhất trong toàn hệ thống.',
        'Hệ thống cập nhật bản ghi Account.',
        'Hệ thống hiển thị MSG15.',
      ],
      brs: [
        { step: 4, desc: 'Họ tên là bắt buộc; nếu để trống, hiển thị thông báo "Họ tên là bắt buộc."' },
        { step: 5, desc: 'Nếu số điện thoại đã được tài khoản khác sử dụng, hiển thị MSG20.' },
      ],
    },
    {
      id: 'UC5', name: 'Đổi mật khẩu',
      objective: 'Cho phép khách hàng đổi mật khẩu tài khoản với xác thực OTP qua email.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng yêu cầu đổi mật khẩu từ màn hình Cài đặt tài khoản.',
      pre: 'Khách hàng đã đăng nhập. • Khách hàng có email đã xác thực trên hệ thống.',
      post: 'Account.PasswordHash được cập nhật theo mật khẩu mới.',
      steps: [
        'Khách hàng mở màn hình Đổi mật khẩu.',
        'Khách hàng nhấn "Gửi OTP đến email".',
        'Notification Service sinh mã OTP 6 chữ số và gửi đến email đã đăng ký qua Email SMTP.',
        'Khách hàng nhập mã OTP và mật khẩu mới.',
        'Khách hàng gửi biểu mẫu.',
        'Hệ thống xác thực OTP (chưa hết hạn, chưa sử dụng).',
        'Hệ thống băm mật khẩu mới và cập nhật Account.PasswordHash.',
        'Hệ thống hiển thị MSG16.',
      ],
      brs: [
        { step: 3, desc: 'OTP có hiệu lực 5 phút kể từ khi sinh mã (CBR3).' },
        { step: 6, desc: 'Nếu OTP hết hạn, hiển thị MSG4. Nếu sai hoặc đã dùng, hiển thị MSG5.' },
        { step: 7, desc: 'Mật khẩu mới không được để trống và được lưu dưới dạng băm mật mã.' },
      ],
    },
    {
      id: 'UC6', name: 'Quản lý tài khoản người dùng',
      objective: 'Cho phép nhân viên xem danh sách tài khoản người dùng và kích hoạt/vô hiệu hóa tài khoản.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên mở màn hình Quản lý tài khoản.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên.',
      post: 'Danh sách người dùng được trả về và hiển thị. • Trạng thái IsActive của tài khoản được cập nhật (nếu có thao tác).',
      steps: [
        'Nhân viên mở màn hình Quản lý tài khoản.',
        'Hệ thống (Account Service) truy vấn danh sách tất cả tài khoản: họ tên, email, số điện thoại, vai trò, trạng thái.',
        'Hệ thống trả về danh sách người dùng và hiển thị cho nhân viên.',
        'Nhân viên có thể tìm kiếm theo tên, email hoặc số điện thoại.',
        'Nhân viên chọn một tài khoản và thao tác kích hoạt hoặc vô hiệu hóa.',
        'Hệ thống cập nhật Account.IsActive và hiển thị MSG22.',
      ],
      brs: [
        { step: 5, desc: 'Nhân viên không thể vô hiệu hóa chính tài khoản đang đăng nhập. Nếu cố thao tác, hệ thống từ chối và hiển thị MSG27.' },
        { step: 6, desc: 'Tài khoản bị vô hiệu hóa (IsActive = false) không thể đăng nhập vào hệ thống — xem UC1 bước 5.' },
      ],
    },
  ],
  vehicle: [
    {
      id: 'UC7', name: 'Xem danh sách xe',
      objective: 'Cho phép khách hàng xem tất cả xe đã đăng ký trong tài khoản.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng mở mục Xe của tôi.',
      pre: 'Khách hàng đã đăng nhập.',
      post: 'Danh sách xe được hiển thị với biển số và loại xe.',
      steps: [
        'Khách hàng mở màn hình Xe của tôi trên Mobile Web.',
        'Hệ thống truy vấn tất cả bản ghi Vehicle có CustomerId trùng với khách hàng đang đăng nhập.',
        'Hệ thống hiển thị danh sách: biển số, hãng xe, loại xe.',
      ],
      brs: [],
    },
    {
      id: 'UC8', name: 'Đăng ký xe',
      objective: 'Cho phép khách hàng thêm xe mới với biển số được xác thực bằng OTP.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng nhấn "Thêm xe" và gửi biển số.',
      pre: 'Khách hàng đã đăng nhập. • Biển số chưa được đăng ký trong tài khoản của khách hàng này.',
      post: 'Bản ghi Vehicle mới được tạo và liên kết với khách hàng. Hiển thị MSG17.',
      steps: [
        'Khách hàng mở màn hình Thêm xe.',
        'Khách hàng nhập biển số và loại xe (tùy chọn).',
        'Khách hàng nhấn "Gửi OTP".',
        'Hệ thống kiểm tra định dạng biển số theo biểu thức chính quy biển số Việt Nam.',
        'Hệ thống kiểm tra biển số chưa được đăng ký trong tài khoản này.',
        'Notification Service sinh mã OTP 6 chữ số và gửi đến email đã đăng ký của khách hàng.',
        'Khách hàng nhập mã OTP.',
        'Khách hàng nhấn Xác thực & Lưu.',
        'Hệ thống xác thực OTP (chưa hết hạn, chưa sử dụng).',
        'Hệ thống lưu bản ghi Vehicle với biển số đã được chuẩn hóa (CBR4).',
        'Hệ thống hiển thị MSG17.',
      ],
      brs: [
        { step: 4, desc: 'Nếu định dạng biển số không hợp lệ, hiển thị MSG8.' },
        { step: 5, desc: 'Nếu biển số đã được đăng ký trong tài khoản này, hiển thị MSG7.' },
        { step: 6, desc: 'OTP gắn với tổ hợp email + biển số, hết hạn sau 5 phút (CBR3).' },
        { step: 9, desc: 'Nếu OTP hết hạn, hiển thị MSG4. Nếu sai hoặc đã dùng, hiển thị MSG5.' },
        { step: 10, desc: 'Ràng buộc duy nhất: (CustomerId, LicensePlate). Biển số được chuẩn hóa trước khi lưu (CBR4).' },
      ],
    },
    {
      id: 'UC9', name: 'Xóa xe',
      objective: 'Cho phép khách hàng xóa một xe đã đăng ký khỏi tài khoản.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng chọn một xe và xác nhận xóa.',
      pre: 'Khách hàng đã đăng nhập. • Xe thuộc về khách hàng đang đăng nhập.',
      post: 'Bản ghi Vehicle bị xóa khỏi cơ sở dữ liệu. Hiển thị MSG18.',
      steps: [
        'Khách hàng chọn một xe trong danh sách Xe của tôi.',
        'Khách hàng nhấn Xóa và xác nhận thao tác.',
        'Hệ thống kiểm tra xe thuộc về khách hàng đang đăng nhập (CBR5).',
        'Hệ thống kiểm tra xe có bản ghi Booking liên quan hay không.',
        'Nếu không có booking: hệ thống xóa bản ghi Vehicle và hiển thị MSG18.',
        'Nếu đã có booking: hệ thống chặn thao tác xóa và hiển thị MSG6.',
      ],
      brs: [
        { step: 4, desc: 'Xe có lịch sử đặt lịch (bất kỳ trạng thái nào) không thể bị xóa nhằm bảo toàn dữ liệu lịch sử.' },
        { step: 6, desc: 'Hiển thị MSG6: "Không thể xóa xe đã có lịch sử đặt lịch."' },
      ],
    },
  ],
};
