// UC data — Phần 2: Dịch vụ & Đặt lịch, Hàng chờ, Thông báo
module.exports = {
  booking: [
    {
      id: 'UC10', name: 'Xem dịch vụ',
      objective: 'Cho phép khách hàng xem tất cả dịch vụ rửa xe và dịch vụ bổ sung (add-on) đang khả dụng.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng mở trang Dịch vụ hoặc Đặt lịch.',
      pre: 'Khách hàng đã đăng nhập.',
      post: 'Danh sách dịch vụ đang hoạt động được hiển thị: tên, giá, thời lượng dự kiến, phân loại.',
      steps: [
        'Khách hàng mở màn hình Dịch vụ/Đặt lịch trên Mobile Web.',
        'Hệ thống truy vấn tất cả bản ghi Service có IsActive = true.',
        'Hệ thống phân nhóm: dịch vụ chính (Cơ bản, Cao cấp, Đặc biệt) và dịch vụ bổ sung (Add-On).',
        'Hệ thống hiển thị cho mỗi dịch vụ: tên, mô tả, giá (VND), thời lượng dự kiến (phút).',
      ],
      brs: [
        { step: 2, desc: 'Chỉ hiển thị cho khách hàng các dịch vụ có IsActive = true.' },
      ],
    },
    {
      id: 'UC11', name: 'Quản lý dịch vụ',
      objective: 'Cho phép nhân viên thêm, cập nhật và kích hoạt/vô hiệu hóa dịch vụ rửa xe.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên mở màn hình Quản lý dịch vụ và thao tác trên danh mục dịch vụ.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên.',
      post: 'Danh mục dịch vụ được cập nhật: bản ghi Service được tạo mới hoặc sửa đổi. Hiển thị MSG21.',
      steps: [
        'Nhân viên mở màn hình Quản lý dịch vụ.',
        'Hệ thống (Booking Service) hiển thị toàn bộ danh mục dịch vụ, gồm cả dịch vụ đang bị vô hiệu hóa.',
        'Nhân viên tạo dịch vụ mới hoặc chọn một dịch vụ để chỉnh sửa.',
        'Nhân viên nhập/chỉnh sửa: tên dịch vụ, mô tả, phân loại, giá cơ bản, thời lượng dự kiến, trạng thái hoạt động.',
        'Nhân viên nhấn Lưu.',
        'Hệ thống kiểm tra tính hợp lệ của dữ liệu: tên không trống, giá và thời lượng là số dương.',
        'Hệ thống lưu bản ghi Service và hiển thị MSG21.',
      ],
      brs: [
        { step: 4, desc: 'Không xóa cứng dịch vụ đã từng được sử dụng trong booking; thay vào đó đặt IsActive = false để bảo toàn dữ liệu lịch sử.' },
        { step: 6, desc: 'Giá cơ bản (BasePrice) phải ≥ 0 VND; thời lượng dự kiến phải ≥ 1 phút. Nếu vi phạm, từ chối lưu và hiển thị MSG32.' },
      ],
    },
    {
      id: 'UC12', name: 'Tạo đặt lịch',
      objective: 'Cho phép khách hàng đặt lịch rửa xe với lựa chọn dịch vụ, ngày và giờ.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng gửi biểu mẫu đặt lịch với xe, dịch vụ, ngày và giờ.',
      pre: 'Khách hàng đã đăng nhập. • Xe được chọn (nếu có) thuộc về khách hàng.',
      post: 'Bản ghi Booking được tạo với Status = Chờ xác nhận (1). • Bản ghi BookingService được tạo cho từng dịch vụ đã chọn (chụp giá tại thời điểm đặt). • Email xác nhận đặt lịch được gửi đến khách hàng qua Email SMTP. • Hiển thị MSG14.',
      steps: [
        'Khách hàng mở màn hình Tạo đặt lịch.',
        'Hệ thống kiểm tra khách hàng có ít nhất một xe đã đăng ký.',
        'Khách hàng chọn một xe, một dịch vụ chính và các dịch vụ bổ sung (tùy chọn).',
        'Khách hàng chọn ngày và giờ đặt lịch.',
        'Hệ thống kiểm tra quyền sở hữu xe (CBR5).',
        'Hệ thống kiểm tra thời gian đặt lịch phải cách hiện tại ít nhất 15 phút và không quá 7 ngày.',
        'Hệ thống kiểm tra khung giờ được chọn có ít hơn 3 lượt đặt (CBR7).',
        'Hệ thống kiểm tra không có booking trùng cho cùng xe trong cùng khung giờ.',
        'Hệ thống kiểm tra tất cả dịch vụ được chọn đang hoạt động.',
        'Hệ thống tính giá: FinalPrice = tổng giá của các dịch vụ đã chọn (CBR6).',
        'Hệ thống hiển thị màn hình tóm tắt: xe, dịch vụ, ngày giờ, thành tiền.',
        'Khách hàng xem lại tóm tắt và nhấn Xác nhận.',
        'Hệ thống lưu Booking và BookingService trong một giao dịch cơ sở dữ liệu duy nhất (CBR9).',
        'Notification Service tạo thông báo xác nhận đặt lịch và gửi email xác nhận qua Email SMTP (ET2).',
        'Hệ thống hiển thị MSG14.',
      ],
      brs: [
        { step: 2, desc: 'Nếu khách hàng chưa đăng ký xe nào, chặn tạo đặt lịch, hiển thị MSG28 và điều hướng sang màn hình Đăng ký xe (UC8).' },
        { step: 5, desc: 'Nếu xe không thuộc về khách hàng, hiển thị MSG9.' },
        { step: 6, desc: 'Nếu thời gian đặt cách hiện tại dưới 15 phút, hiển thị MSG10. Cửa sổ đặt lịch tối đa là 7 ngày kể từ ngày hiện tại.' },
        { step: 7, desc: 'Tối đa 3 lượt đặt trên mỗi khung 1 giờ trên toàn hệ thống. Nếu vượt, hiển thị MSG11.' },
        { step: 8, desc: 'Cùng một xe không thể có hai booking trong cùng khung 1 giờ. Nếu trùng, hiển thị MSG12.' },
        { step: 9, desc: 'Nếu có dịch vụ được chọn với IsActive = false, hiển thị MSG13.' },
        { step: 12, desc: 'Nếu khách hàng không xác nhận, quay lại bước chọn dịch vụ; chưa có dữ liệu nào được lưu vào hệ thống.' },
        { step: 13, desc: 'Toàn bộ thao tác tạo booking dùng giao dịch CSDL để tránh tranh chấp dữ liệu (CBR9).' },
      ],
    },
    {
      id: 'UC13', name: 'Xem đặt lịch',
      objective: 'Cho phép khách hàng xem các booking hiện tại và lịch sử rửa xe.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng mở màn hình Đặt lịch của tôi.',
      pre: 'Khách hàng đã đăng nhập.',
      post: 'Danh sách booking hiển thị theo thứ tự mới nhất trước; booking đang hoạt động hiển thị kèm tiến độ hàng chờ theo thời gian thực.',
      steps: [
        'Khách hàng mở màn hình Đặt lịch của tôi trên Mobile Web.',
        'Hệ thống truy vấn tất cả bản ghi Booking có CustomerId trùng với khách hàng đang đăng nhập, sắp xếp theo ScheduledAt giảm dần.',
        'Hệ thống hiển thị cho mỗi booking: biển số xe, tên dịch vụ, ngày giờ hẹn, trạng thái, giá cuối.',
        'Nếu có booking đang hoạt động (Chờ xác nhận / Đã xác nhận / Đã check-in): hệ thống truy vấn thêm bản ghi Queue liên quan.',
        'Nếu có bản ghi Queue: hệ thống hiển thị vị trí hàng chờ và công đoạn rửa hiện tại.',
      ],
      brs: [
        { step: 4, desc: 'Nếu không có booking đang hoạt động, hiển thị thông báo "Bạn không có lịch đặt đang hoạt động" kèm liên kết tạo booking mới.' },
      ],
    },
    {
      id: 'UC14', name: 'Xác nhận đặt lịch',
      objective: 'Cho phép nhân viên xác nhận một booking đang ở trạng thái Chờ xác nhận.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên nhấn Xác nhận trên một booking trong danh sách booking.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên. • Booking tồn tại với Status = Chờ xác nhận (1).',
      post: 'Booking.Status = Đã xác nhận (2). • Chi tiết booking được trả về cho nhân viên. • Thông báo cập nhật được gửi cho khách hàng.',
      steps: [
        'Nhân viên mở danh sách booking chờ xử lý.',
        'Hệ thống (Booking Service) trả về chi tiết booking: khách hàng, biển số, dịch vụ, ngày giờ hẹn.',
        'Nhân viên xem xét và nhấn Xác nhận.',
        'Hệ thống kiểm tra Booking.Status hiện tại là Chờ xác nhận.',
        'Hệ thống cập nhật Booking.Status = Đã xác nhận.',
        'Notification Service tạo thông báo xác nhận cho khách hàng.',
        'Hệ thống hiển thị MSG24.',
      ],
      brs: [
        { step: 4, desc: 'Chỉ booking ở trạng thái Chờ xác nhận mới có thể được xác nhận.' },
        { step: 4, desc: 'Nếu booking không còn ở trạng thái Chờ xác nhận tại thời điểm xác nhận (đã bị xử lý bởi thao tác khác — tranh chấp đồng thời), từ chối cập nhật, hiển thị MSG29 và yêu cầu nhân viên tải lại danh sách.' },
      ],
    },
    {
      id: 'UC15', name: 'Hủy đặt lịch',
      objective: 'Cho phép nhân viên hủy một booking theo yêu cầu của khách hàng hoặc theo tình huống vận hành.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên nhấn Hủy trên một booking.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên. • Booking tồn tại với Status = Chờ xác nhận hoặc Đã xác nhận.',
      post: 'Booking.Status = Đã hủy (5). • Thông báo hủy được gửi cho khách hàng.',
      steps: [
        'Nhân viên chọn một booking và nhấn Hủy.',
        'Hệ thống kiểm tra Booking.Status là Chờ xác nhận hoặc Đã xác nhận.',
        'Nhân viên xác nhận thao tác hủy.',
        'Hệ thống cập nhật Booking.Status = Đã hủy.',
        'Notification Service tạo thông báo hủy cho khách hàng.',
        'Hệ thống hiển thị MSG25.',
      ],
      brs: [
        { step: 2, desc: 'Booking ở trạng thái Đã check-in, Hoàn tất hoặc Đã hủy không thể bị hủy qua chức năng này. Nếu cố thao tác, hiển thị MSG30.' },
      ],
    },
  ],
  queue: [
    {
      id: 'UC16', name: 'Xem hàng chờ hôm nay',
      objective: 'Cho phép nhân viên xem danh sách hợp nhất tất cả xe trong ngày hiện tại.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên mở màn hình Quản lý hàng chờ.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên.',
      post: 'Danh sách hàng chờ trong ngày được trả về, sắp xếp theo thời gian check-in (FIFO).',
      steps: [
        'Nhân viên mở màn hình Quản lý hàng chờ.',
        'Hệ thống (Queue Service) truy vấn tất cả bản ghi Queue trong ngày (CheckInAt = hôm nay), loại trừ trạng thái Hoàn tất và Đã hủy.',
        'Hệ thống truy vấn các Booking có lịch hẹn hôm nay với Status = Chờ xác nhận hoặc Đã xác nhận (mục chờ ảo).',
        'Hệ thống gộp và khử trùng lặp hai danh sách (mục Queue thực ưu tiên hơn mục booking ảo của cùng một xe).',
        'Hệ thống sắp xếp danh sách theo CheckInAt tăng dần (đến trước phục vụ trước — CBR8).',
        'Hệ thống trả về danh sách hàng chờ, hiển thị mỗi mục: vị trí, biển số, tên khách hàng, trạng thái hiện tại, giờ hẹn, ghi chú nhân viên.',
      ],
      brs: [
        { step: 4, desc: 'Mục booking ảo (chưa check-in) được phân biệt trực quan với mục hàng chờ thực.' },
      ],
    },
    {
      id: 'UC17', name: 'Check-in khách hàng',
      objective: 'Cho phép nhân viên đưa xe của khách vào hàng chờ khi xe đến trung tâm, tự động phát hiện booking nếu có.',
      actors: 'Nhân viên',
      trigger: 'Xe đến trung tâm; nhân viên nhập biển số (hoặc dùng kết quả quét LPR — UC18) trên biểu mẫu Check-in.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên.',
      post: 'Bản ghi Queue mới được tạo với Status = Đang chờ. • Nếu xe có booking hôm nay: booking được liên kết, Booking.Status = Đã check-in (3), danh sách dịch vụ được nạp sẵn.',
      steps: [
        'Nhân viên nhập biển số xe (thủ công hoặc từ kết quả quét LPR — UC18) và tên khách (tùy chọn) trên biểu mẫu Check-in.',
        'Nhân viên gửi biểu mẫu.',
        'Hệ thống chuẩn hóa biển số (CBR4).',
        'Hệ thống tìm bản ghi Vehicle khớp với biển số đã chuẩn hóa.',
        'Nếu tìm thấy xe: hệ thống lấy tên khách hàng liên kết.',
        'Nếu không tìm thấy xe: hệ thống dùng tên khách do nhân viên nhập (khách vãng lai).',
        'Hệ thống tìm Booking của xe này có lịch hẹn hôm nay với Status = Chờ xác nhận hoặc Đã xác nhận.',
        'Nếu tìm thấy booking: hệ thống liên kết Queue với Booking, cập nhật Booking.Status = Đã check-in và nạp sẵn danh sách dịch vụ đã đặt.',
        'Hệ thống tạo bản ghi Queue mới: Status = Đang chờ, LicensePlate = biển số chuẩn hóa, Position = vị trí kế tiếp theo thứ tự đến.',
      ],
      brs: [
        { step: 3, desc: 'Bắt buộc chuẩn hóa biển số trước mọi thao tác tra cứu (CBR4).' },
        { step: 8, desc: 'Khi booking được liên kết tự động, thông tin dịch vụ đã đặt được nạp sẵn vào mục hàng chờ để nhân viên tham chiếu.' },
        { step: 9, desc: 'Vị trí hàng chờ được gán theo thứ tự check-in — đến trước phục vụ trước (CBR8).' },
      ],
    },
    {
      id: 'UC18', name: 'Quét biển số (LPR)',
      objective: 'Cho phép nhân viên quét biển số xe tự động bằng Camera LPR thay vì nhập thủ công.',
      actors: 'Nhân viên; Hệ thống ngoài: Camera LPR, 3rd-party LPR API',
      trigger: 'Nhân viên nhấn nút "Quét biển số" khi xe dừng tại vị trí camera.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên. • Camera LPR và 3rd-party LPR API đang hoạt động và được cấu hình.',
      post: 'Chuỗi biển số được trích xuất và điền vào biểu mẫu Check-in (UC17).',
      steps: [
        'Nhân viên nhấn nút "Quét biển số" trên màn hình hàng chờ.',
        'Hệ thống (LPR Service) gửi yêu cầu chụp ảnh biển số (request plate scan) đến Camera LPR.',
        'Camera LPR chụp ảnh biển số của xe.',
        'Ảnh được gửi đến 3rd-party LPR API (hệ thống ngoài) để nhận dạng.',
        '3rd-party LPR API trích xuất chuỗi biển số từ ảnh và trả về cho LPR Service của hệ thống.',
        'LPR Service chuẩn hóa chuỗi biển số nhận được (CBR4).',
        'Hệ thống điền biển số vào biểu mẫu Check-in để nhân viên xác nhận (tiếp tục UC17).',
      ],
      brs: [
        { step: 2, desc: 'Nếu Camera LPR không phản hồi yêu cầu chụp trong 5 giây, hiển thị MSG23 và cho phép nhân viên nhập biển số thủ công.' },
        { step: 5, desc: 'Nếu 3rd-party LPR API không nhận dạng được biển số hoặc trả về lỗi, hiển thị MSG23 và cho phép nhân viên nhập biển số thủ công.' },
        { step: 7, desc: 'Nhân viên luôn có thể sửa lại chuỗi biển số do LPR trả về trước khi check-in.' },
      ],
    },
    {
      id: 'UC19', name: 'Chuyển trạng thái rửa xe',
      objective: 'Cho phép nhân viên chuyển một xe sang công đoạn rửa kế tiếp trong quy trình.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên nhấn nút Chuyển tiếp trên một mục hàng chờ.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên. • Mục hàng chờ tồn tại với trạng thái chưa kết thúc (không phải Hoàn tất/Đã hủy).',
      post: 'Queue.Status được cập nhật sang công đoạn kế tiếp. StartedAt/CompletedAt được ghi nhận khi thích hợp.',
      steps: [
        'Nhân viên chọn một mục trong danh sách hàng chờ.',
        'Nhân viên nhấn nút Chuyển tiếp.',
        'Hệ thống xác định trạng thái kế tiếp dựa trên trạng thái hiện tại (xem sơ đồ chuyển trạng thái 2.4.2).',
        'Hệ thống cập nhật Queue.Status sang công đoạn kế tiếp.',
        'Nếu chuyển từ Đang chờ: hệ thống ghi Queue.StartedAt = thời điểm hiện tại.',
        'Nếu chuyển sang Hoàn tất: hệ thống ghi Queue.CompletedAt = thời điểm hiện tại.',
      ],
      brs: [
        { step: 3, desc: 'Trình tự trạng thái: Đang chờ → Quét LPR → Đang rửa → Xử lý add-on → Sấy khô → Hoàn tất.' },
        { step: 2, desc: 'Nếu trạng thái là Hoàn tất hoặc Đã hủy, nút Chuyển tiếp bị vô hiệu hóa; nếu vẫn cố gửi yêu cầu, hệ thống từ chối và hiển thị MSG31.' },
      ],
    },
    {
      id: 'UC20', name: 'Cập nhật hàng chờ',
      objective: 'Cho phép nhân viên cập nhật thủ công trạng thái và/hoặc thêm ghi chú cho một mục hàng chờ.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên gửi cập nhật cho một mục hàng chờ cụ thể.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên.',
      post: 'Mục hàng chờ được cập nhật. Nếu chưa có mục hàng chờ cho booking, một bản ghi Queue mới được tạo.',
      steps: [
        'Nhân viên chọn một mục hàng chờ hoặc cung cấp mã booking/queue.',
        'Nhân viên nhập trạng thái mới và/hoặc ghi chú.',
        'Nhân viên gửi cập nhật.',
        'Hệ thống kiểm tra bản ghi Queue có tồn tại với mã đã cho hay không.',
        'Nếu có: hệ thống cập nhật Queue.Status (nếu cung cấp) và Queue.StaffNote (nếu cung cấp).',
        'Nếu chưa có Queue cho booking: hệ thống tạo bản ghi Queue mới với trạng thái được cung cấp.',
      ],
      brs: [],
    },
    {
      id: 'UC21', name: 'Check-out khách hàng',
      objective: 'Hoàn tất dịch vụ rửa xe, cập nhật thống kê khách hàng và gửi thông báo hoàn tất.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên nhấn Check-out trên mục hàng chờ đã hoàn tất công đoạn sấy khô.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên. • Mục hàng chờ tồn tại và chưa ở trạng thái Hoàn tất/Đã hủy.',
      post: 'Queue.Status = Hoàn tất; Booking.Status = Hoàn tất (4). • Queue.CompletedAt được ghi nhận. • Thống kê khách hàng cập nhật: TotalVisits + 1, TotalSpend + FinalPrice, LastVisitAt = hiện tại. • Email thông báo rửa xe hoàn tất được gửi cho khách hàng (ET3).',
      steps: [
        'Nhân viên chọn mục hàng chờ và nhấn Check-out.',
        'Hệ thống cập nhật Queue.Status = Hoàn tất và Booking.Status = Hoàn tất.',
        'Hệ thống ghi Queue.CompletedAt = thời điểm hiện tại.',
        'Hệ thống lấy Booking.FinalPrice để chốt số tiền thanh toán.',
        'Hệ thống cập nhật Customer: TotalVisits += 1, TotalSpend += FinalPrice, LastVisitAt = hiện tại.',
        'Notification Service tạo thông báo "rửa xe hoàn tất" cho khách hàng và gửi email qua Email SMTP (ET3).',
      ],
      brs: [
        { step: 4, desc: 'Với khách vãng lai không có booking, nhân viên nhập số tiền thanh toán dựa trên các dịch vụ đã thực hiện.' },
        { step: 6, desc: 'Thông báo hoàn tất chỉ được gửi khi khách hàng có tài khoản (có email liên kết).' },
      ],
    },
    {
      id: 'UC22', name: 'Hủy lượt hàng chờ',
      objective: 'Cho phép nhân viên hủy một xe khỏi hàng chờ đang hoạt động.',
      actors: 'Nhân viên',
      trigger: 'Nhân viên nhấn Hủy trên một mục hàng chờ.',
      pre: 'Người dùng đã đăng nhập với vai trò Nhân viên. • Mục hàng chờ tồn tại và Status khác Hoàn tất.',
      post: 'Queue.Status = Đã hủy. Booking liên kết (nếu có) chuyển Status = Đã hủy.',
      steps: [
        'Nhân viên chọn một mục hàng chờ và nhấn Hủy.',
        'Hệ thống kiểm tra trạng thái mục hàng chờ khác Hoàn tất.',
        'Hệ thống cập nhật Queue.Status = Đã hủy.',
        'Nếu mục hàng chờ có Booking liên kết (BookingId khác null): hệ thống cập nhật Booking.Status = Đã hủy (5).',
      ],
      brs: [
        { step: 2, desc: 'Mục hàng chờ đã Hoàn tất không thể bị hủy. Hiển thị MSG19 nếu cố thao tác.' },
      ],
    },
  ],
  notification: [
    {
      id: 'UC23', name: 'Xem thông báo',
      objective: 'Cho phép khách hàng xem tất cả thông báo của hệ thống.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng mở bảng Thông báo.',
      pre: 'Khách hàng đã đăng nhập.',
      post: 'Tất cả thông báo hiển thị theo thứ tự mới nhất trước, kèm chỉ báo đã đọc/chưa đọc.',
      steps: [
        'Khách hàng mở màn hình Thông báo trên Mobile Web.',
        'Hệ thống (Notification Service) truy vấn tất cả bản ghi Notification có CustomerId trùng với khách hàng đang đăng nhập.',
        'Hệ thống sắp xếp theo CreatedAt giảm dần.',
        'Hệ thống hiển thị: tiêu đề, nội dung, loại thông báo (Đặt lịch / Hoàn tất / Hệ thống), thời gian, trạng thái đọc.',
      ],
      brs: [],
    },
    {
      id: 'UC24', name: 'Đánh dấu thông báo đã đọc',
      objective: 'Cho phép khách hàng đánh dấu một thông báo cụ thể là đã đọc.',
      actors: 'Khách hàng',
      trigger: 'Khách hàng nhấn vào hoặc mở một thông báo.',
      pre: 'Khách hàng đã đăng nhập. • Thông báo thuộc về khách hàng đang đăng nhập.',
      post: 'Notification.IsRead = true.',
      steps: [
        'Khách hàng nhấn vào một thông báo.',
        'Hệ thống kiểm tra Notification.CustomerId trùng với khách hàng đang đăng nhập (CBR5).',
        'Hệ thống đặt Notification.IsRead = true.',
      ],
      brs: [
        { step: 2, desc: 'Bắt buộc kiểm tra quyền sở hữu để ngăn khách hàng đánh dấu thông báo của khách hàng khác.' },
      ],
    },
  ],
};
